import { useEffect, useState } from "react";
import {
  DEFAULT_BBOX,
  fetchColumn,
  fetchFlatSlices,
  fetchModel,
  fetchVariables,
  fetchVoxelGrid,
} from "../services/api";
import useVizStore from "../store/vizStore";

/**
 * Loads model-layer payloads from the store's current variable / depth / time.
 * Person 1 should read this (and the store) — do not edit this file from globe/.
 *
 * Returns:
 *   variables  — GET /api/variables catalog
 *   field      — GET /api/model/{variable} scalar field at current depth
 *   slices     — explore flat-slice bands (when exploreRenderer === "flat-slice")
 *   voxels     — explore voxel grid (when exploreRenderer === "voxel")
 *   column     — inspect-mode drill-core at anchorPoint
 */
export default function useModelData({ bbox } = {}) {
  const region = bbox ?? DEFAULT_BBOX;
  const west = region.west;
  const south = region.south;
  const east = region.east;
  const north = region.north;

  const variable = useVizStore((s) => s.variable);
  const depth = useVizStore((s) => s.depth);
  const time = useVizStore((s) => s.time);
  const mode = useVizStore((s) => s.mode);
  const exploreRenderer = useVizStore((s) => s.exploreRenderer);
  const anchorLat = useVizStore((s) => s.anchorPoint?.lat ?? null);
  const anchorLon = useVizStore((s) => s.anchorPoint?.lon ?? null);

  const [variables, setVariables] = useState(null);
  const [field, setField] = useState(null);
  const [slices, setSlices] = useState(null);
  const [voxels, setVoxels] = useState(null);
  const [column, setColumn] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    let cancelled = false;

    fetchVariables()
      .then((data) => {
        if (!cancelled) setVariables(data);
      })
      .catch((err) => {
        if (!cancelled) setError(err);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);

    const load = async () => {
      const queryBbox = { west, south, east, north };
      const nextField = await fetchModel(variable, { depth, time, bbox: queryBbox });
      if (cancelled) return;
      setField(nextField);

      if (mode === "explore" && exploreRenderer === "flat-slice") {
        const nextSlices = await fetchFlatSlices(variable, { time, bbox: queryBbox });
        if (cancelled) return;
        setSlices(nextSlices);
        setVoxels(null);
      } else if (mode === "explore" && exploreRenderer === "voxel") {
        const nextVoxels = await fetchVoxelGrid(variable, { time, bbox: queryBbox });
        if (cancelled) return;
        setVoxels(nextVoxels);
        setSlices(null);
      } else {
        setSlices(null);
        setVoxels(null);
      }

      if (mode === "inspect" && anchorLat != null && anchorLon != null) {
        const nextColumn = await fetchColumn({
          lat: anchorLat,
          lon: anchorLon,
          time,
        });
        if (cancelled) return;
        setColumn(nextColumn);
      } else {
        setColumn(null);
      }
    };

    load()
      .catch((err) => {
        if (!cancelled) setError(err);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [
    variable,
    depth,
    time,
    mode,
    exploreRenderer,
    anchorLat,
    anchorLon,
    west,
    south,
    east,
    north,
  ]);

  const currentVariableMeta =
    variables?.variables?.find((v) => v.id === variable) ?? null;

  return {
    variables,
    currentVariableMeta,
    field,
    slices,
    voxels,
    column,
    loading,
    error,
  };
}
